name: AutoPay
version: 1.0.0
main: com.autopay.AutoPay
api-version: 1.20
description: 自動給玩家錢的插件
author: YourName

commands:
  autopay:
    description: 控制自動付款通知
    usage: /<command> [on|off|status]
    permission: autopay.use
    permission-message: 您沒有權限使用此指令

permissions:
  autopay.use:
    description: 允許使用自動付款指令
    default: true
  autopay.admin:
    description: 允許管理自動付款設置
    default: op
